# bridge_qos.yaml
/**:
  ros__parameters:
    qos_overrides:
      /camera/image_raw:
        publisher:
          reliability: "reliable"
          history: "keep_last"
          depth: 1
      # ADD THIS BLOCK FOR LIDAR
      /scan:
        publisher:
          reliability: "reliable"
          history: "keep_last"
          depth: 1